### ISSUE TITLE
Automate slack invites

### ISSUE THREAD

**Issue by skorasaurus** [opencleveland/opencleveland.github.io#12]
Would be nice to allow people to request their own invite to our slack team. 

can be done via https://github.com/outsideris/slack-invite-automation

**Comment by pkoepke** [comment]
Is this a significant burden today? It seems we would want to know and approve anyone joining or channel. I'm all for automation and being open to new people, but maybe this is something where we want a person in the prices?

**Comment by skorasaurus** [comment]
if we do, check https://sac-tech.herokuapp.com/

**Comment by cwang912** [comment]
I think it could help drive some growth – there are always private channels if you need to protect things? What goes on now that wouldn't be ok to be public? 

I mean, we are *Open* Cleveland.

**Comment by skorasaurus** [comment]
yeah, thinking about this more, and at the least, we should have a landing page for slack....

**Comment by skorasaurus** [comment]
https://github.com/rauchg/slackin

**Comment by nicolamattina** [comment]
Also check this one. With Stamplay, you can create a web app to automate Slack invites: 
https://blog.stamplay.com/launch-your-community-with-a-fully-automated-slack-signup-page/

**Comment by skorasaurus** [comment]
DONE AT https://opencle-slack.herokuapp.com/ 
a
THANKS TO @ysakthi
