### ISSUE TITLE
Create Google Analytics account for Open Cleveland, use that for site analytics.  

### ISSUE THREAD

**Issue by pkoepke** [opencleveland/opencleveland.github.io#5]
At the moment I have a Google Analytics script monitoring the web page, but it's on my personal Analytics account. I can share the dashboard reports with anyone who wants them, but long-term we should probably have an Analytics account for the whole organization. We can probably use the open.cleveland@gmail.com account for that.

This is related to Flu Shots issue 5: https://github.com/opencleveland/flu-shots/issues/5

**Comment by skorasaurus** [comment]
We've had one (thanks to @pkoepke) but he's listed as the administrator (including adding/removing users) and it's best in the future to just have opencleveland's gmail account as the administrator. 

after speaking to him, he suggested should just start from scratch; and it's no big deal if we lose the historical analytics. 

next steps, create new property underneath the 'opencleveland' account in analytics and then update analytics ID in this https://github.com/opencleveland/opencleveland.github.io/blob/476d636b0d360584b82a54d71b42f0a2bccaab79/_includes/footer.html

cc @foxbjk

**Comment by skorasaurus** [comment]
done in https://github.com/opencleveland/opencleveland.github.io/pull/49 ; 

uses opencleveland gmail account as administrator.
